name: React Selenium Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install frontend dependencies
        run: npm install


  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20
      ports:
        - 5000:5000
      options: --network-alias=testserver

    env:
      APP_URL: http://testserver:5000/
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run : npm install

      - name: List files for debugging
        run: |
          echo "Current directory:"
          ls -la
          pwd

      - name: Start Node server
        run: |
          nohup node server.js &
          sleep 5

      - name: Verify server is running
        run: |
          curl -f http://localhost:5000 || { echo "Server failed to start"; exit 1; }

      - name: Wait for Selenium server to be up
        run: |
          for i in {1..10}; do
            curl -s $SELENIUM_HOST && break || sleep 3
          done

      - name: Run Selenium tests
        run: node selenium-test.js
